    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    logging:
      file:
        name: ./cadastro.log
#    path: ./
#  level:
#    root: info